### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by mboiar** [mboiar/SimplyType#2]
### Description
Design and implement a user interface for the game.

### Sub-tasks
- [ ] Create UI/UX design of the game
- [x] Choose GUI framework
- [ ] Implement the interface
